# Generated by Django 4.0.4 on 2022-05-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_course_headman_course_headman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='social_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
