# Generated by Django 4.0.4 on 2022-05-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_person_email_person_social_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='course',
            name='headman',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='student.course'),
        ),
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(null=True, to='student.subject'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_of_lesson',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='student.group'),
        ),
        migrations.AddField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(null=True, to='student.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='curator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='student.person'),
        ),
        migrations.AlterField(
            model_name='group',
            name='headman',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='student.person'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='groups',
        ),
        migrations.AddField(
            model_name='lesson',
            name='groups',
            field=models.ManyToManyField(null=True, to='student.group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='student.subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='student.person'),
        ),
    ]
