# Generated by Django 4.0.4 on 2022-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_course_groups_remove_course_headman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(to='student.subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='groups',
            field=models.ManyToManyField(to='student.group'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(to='student.course'),
        ),
    ]
